version = 0.1

[default]
[default.global.parameters]
stack_name = "s3-notification-system"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "s3-notification-system-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dev"
s3_prefix = "s3-notification-system-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev EmailSubscription=dev-admin@example.com BucketName=s3-notification-bucket"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-notification-system-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-prod"
s3_prefix = "s3-notification-system-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod EmailSubscription=prod-admin@example.com BucketName=s3-notification-bucket"
