version = 0.1

[default]
[default.global.parameters]
stack_name = "s3-notification-system"
fail_on_empty_changeset = false

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "s3-notification-system-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dev-week8"
s3_prefix = "s3-notification-system-dev"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev EmailSubscriptionParameter=julius.sowah@amalitech.com BucketName=s3-notification-bucket"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-notification-system-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-prod-week8"
s3_prefix = "s3-notification-system-prod"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod EmailSubscriptionParameter=juliusadjeteysowah@gmail.com BucketName=s3-notification-bucket"
