AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  S3 Event Notification System
  An event-driven architecture that sends email notifications when files are uploaded to S3

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name (dev or prod)

  EmailSubscription:
    Type: String
    Description: Email address to receive S3 upload notifications

  BucketName:
    Type: String
    Description: Name for the S3 bucket (must be globally unique)
    Default: s3-notification-bucket

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  # S3 bucket to store files
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${Environment}"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt S3NotificationFunction.Arn

  # Lambda permission for S3 to invoke function
  S3NotificationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref S3NotificationFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt UploadBucket.Arn

  # SNS Topic for email notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "s3-upload-notifications-${Environment}"
      DisplayName: !Sub "S3 Upload Notifications (${Environment})"

  # Email subscription to the SNS topic
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref EmailSubscription

  # Lambda function to process S3 events
  S3NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.giftedlabs.S3UploadHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
          ENVIRONMENT: !Ref Environment
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - S3ReadPolicy:
            BucketName: !Ref UploadBucket

Outputs:
  S3NotificationFunction:
    Description: "S3 Notification Lambda Function ARN"
    Value: !GetAtt S3NotificationFunction.Arn

  UploadBucket:
    Description: "S3 bucket for file uploads"
    Value: !Ref UploadBucket

  NotificationTopic:
    Description: "SNS Topic ARN for notifications"
    Value: !Ref NotificationTopic

  Region:
    Description: "Region where resources are deployed"
    Value: !Ref AWS::Region