name: SAM Deploy Pipeline

on:
  push:
    branches: [ main, develop ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Set environment based on branch
        id: set-env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_OUTPUT
          fi

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1


      - name: SAM Build
        run: sam build

      - name: Create deployment buckets if they don't exist
        run: |
          ENV=${{ steps.set-env.outputs.ENV}}
          UNIQUE_ID=${{secrets.ACCOUNT_ID}}
          BUCKET_NAME="aws-sam-cli-managed-default-samclisourcebucket-$ENV-$UNIQUE_ID"
          if ! aws s3 ls "s3://$BUCKET_NAME" 2>&1 > /dev/null; then
            aws s3 mb "s3://$BUCKET_NAME" --region eu-central-1
          fi      

      - name: SAM Deploy
        run: |
          sam deploy \
            --config-env ${{ steps.set-env.outputs.ENV }} \
            --no-fail-on-empty-changeset \
            --confirm-changeset \
            --s3-bucket $BUCKET_NAME            
